### ISSUE TITLE
Ability to check data checksums through psql instead of pg_controldata 

### ISSUE THREAD

**Issue by avinashvallarapu** [HexaCluster/pgdsat#1]
Check for data checksums using - 

```
psql -c "select name, setting from pg_settings where name IN ('data_checksums');
```
This will eventually help extending the tool to DBaaS platforms like AWS RDS/Aurora, Azure Database for PostgreSQL and Google Cloud SQL for PostgreSQL.

**Comment by darold** [comment]
The use of pg_controldata allow to run this test on multi-cluster PostgreSQL server, but maybe it is best to have one execution of pgdsat per PostgreSQL cluster. I will also consider modifying this behavior in future release.

**Comment by darold** [comment]
Commit 7a287d6 remove the use of pg_controldata.
