### ISSUE TITLE
"2.4 - Check permissions of pg_hba.conf "Appears twice in the report.html

### ISSUE THREAD

**Issue by sak1** [HexaCluster/pgdsat#11]
I use PGDSAT to build a check for postgresql16, and can get a normal detection report: report.html, just in Detailed security assessment, "2.4 - Check permissions of pg_hba.conf and its description: The pg_hba.conf UNIX permission must be... "Appears twice, may be a small bug, please detect, hope to help the software more perfect.

**Comment by darold** [comment]
Thanks, commit 377f46c fixes this issue.
