### ISSUE TITLE
Ability to check Postgres version through psql instead of scanning PG_VERSION

### ISSUE THREAD

**Issue by avinashvallarapu** [HexaCluster/pgdsat#2]
Scan Postgres version using psql. 

This will eventually help extending the tool to DBaaS platforms like AWS RDS/Aurora, Azure Database for PostgreSQL and Google Cloud SQL for PostgreSQL.

```
psql -c "select name, setting from pg_settings where name IN ('server_version');
```

**Comment by darold** [comment]
This check of PG_VERSION files is part of the CIS Benchmark to check that the PGDATA is correctly initialized but I agree that it is useless in a context of a running server. PostgreSQL won't start  if PG_VERSION files don't match. I will consider changing this behavior in next release.

**Comment by darold** [comment]
Now that we have the infrastructure to exclude some check from the report, best it to define which checks must be removed from the report to be able to run on cloud platforms.
