### ISSUE TITLE
Died at lib/PGDSAT.pm line 1612

### ISSUE THREAD

**Issue by guruguruguru** [HexaCluster/pgdsat#8]
Hey,

I just wanted to test the tool but running it gives me the following error after some time:

`(test) - postgres@XXX-a[pgdsat-1.1] perl -I ./lib ./pgdsat -U postgres -h /tmp -d postgres -o report.html
Died at lib/PGDSAT.pm line 1612.
`
perl-bignum perl-Math-BigRat are installed.

Thanks,
Dennis

**Comment by darold** [comment]
Commit c8c1dbf will prevent pgdsat to die and reports the source of the error. Can you please give it a try and post the error message returned?

**Comment by guruguruguru** [comment]
Sorry, I forgot the errors:
`(test) - postgres@qp-dschwan01-a[pgdsat-1.1] perl -I ./lib ./pgdsat -U postgres -h /tmp -d postgres -o report.html
ERROR: fail to get ip range from ( XXX-b.portaldb.server.lan, trust ). 
ERROR: fail to get ip range from ( XXX-a.portaldb.server.lan, trust ). 
ERROR: fail to get ip range from ( XXX-b.portaldb.server.lan, trust ). 
ERROR: fail to get ip range from ( XXX-a.portaldb.server.lan, trust ). 
ERROR: fail to get ip range from ( XXX.server.lan, scram-sha-256 ). 
ERROR: fail to get ip range from ( localhost, md5 ). 
ERROR: fail to get ip range from ( XXX.portaldb.server.lan, md5 ). 
ERROR: fail to get ip range from ( localhost, md5 ). 
`

**Comment by darold** [comment]
Commit e97463d fixes this issue.
